# Generated by Django 5.1.4 on 2024-12-31 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('json_data', models.JSONField(blank=True, default=None, null=True)),
                ('commune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='security_data.commune')),
            ],
        ),
    ]
