# Generated by Django 5.1.4 on 2024-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to=""),
        ),
    ]
