# Generated by Django 5.1.4 on 2024-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="json_data",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
