# Generated by Django 5.1.4 on 2024-12-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_image_alter_post_json_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="color",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
