# Generated by Django 5.1.4 on 2024-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
