# Generated by Django 5.1.4 on 2024-12-31 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('arrondissement', models.CharField(max_length=20)),
                ('name_capital', models.CharField(max_length=200)),
                ('name_order', models.CharField(max_length=200)),
                ('name_full', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Securite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('agression_class', models.CharField(max_length=200)),
                ('aggression_unity', models.CharField(max_length=200)),
                ('public_value', models.CharField(max_length=20)),
                ('facts_value', models.CharField(max_length=20)),
                ('per_thousand', models.CharField(max_length=20)),
                ('pop', models.CharField(max_length=20)),
                ('millpop', models.CharField(max_length=20)),
                ('commune', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='security_data.commune')),
            ],
        ),
    ]
