# Generated by Django 5.1.4 on 2024-12-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_commune", models.IntegerField()),
                ("region", models.IntegerField()),
                ("department", models.IntegerField()),
                ("arrondissement", models.IntegerField()),
                ("name_capital", models.CharField(max_length=200)),
                ("name_order", models.CharField(max_length=200)),
                ("name_full", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
