# Generated by Django 5.1.4 on 2024-12-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security_data", "0003_alter_commune_arrondissement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Securite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20)),
                ("agression_class", models.CharField(max_length=200)),
                ("aggression_unity", models.CharField(max_length=200)),
                ("public_value", models.CharField(max_length=20)),
                ("facts_value", models.CharField(max_length=20)),
                ("per_thousand", models.CharField(max_length=20)),
                ("complementinfoval", models.CharField(max_length=20)),
                ("complementinfotaux", models.CharField(max_length=20)),
                ("pop", models.CharField(max_length=20)),
                ("millpop", models.CharField(max_length=20)),
                ("log", models.CharField(max_length=20)),
                ("milllog", models.CharField(max_length=20)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security_data.commune",
                    ),
                ),
            ],
        ),
    ]
