# Generated by Django 5.1.4 on 2025-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_commune"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
