# Generated by Django 5.1.4 on 2025-01-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("100", "Admin"),
                    ("99", "Developer"),
                    ("98", "Moderator"),
                    ("3", "User Lvl 3"),
                    ("2", "User Lvl 2"),
                    ("1", "User Lvl 1"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
